Challenge1
muthash/Weconnect-v1 pull request #1
Opened 2018-02-28 17:09 UTC by muthash

The branch challenge1 contains the requested user interfaces which can be accessed for viewing here: https://muthash.github.io/ Kindly review and merge to develop if they meet the required standards. Thank you

2018-02-28 18:26 UTC, peterpaints requested changes
Could you fix the indentation? Most text editors have an auto indent feature that should help

2018-02-28 18:30 UTC, peterpaints commented on designs/UI/register.html
> +        <section>
Did you mean for this section tag to be a closing one? As in </section> ?

2018-02-28 18:31 UTC, peterpaints commented on designs/UI/password_reset.html
> +                        <a class="nav-item nav-link" href="signin.html">Sign in </span></a>
Missing <span> tag here.

2018-02-28 18:33 UTC, peterpaints requested changes
Your code looks good. The pages look good. Fix those small issues I have requested, then I'll merge. Once I merge you can move on.

2018-02-28 20:14 UTC, peterpaints approved these changes

2018-02-28 20:17 UTC, peterpaints requested changes
Changes look good. Now, once 2 of your peers have reviewed, I'll merge it.

2018-02-28 21:23 UTC, JoshuaOndieki commented
I think the link explanations you've given on the homepage would be better placed in a FAQs page.
Alternatively, you could provide tooltips for the respective link buttons.
Great signup form. I commend you for those input tips.
According to my screen size, I have to scroll down to access the full sign up form. I suggest you make the form short. As a user, the first impression if I can't see the signup button for the form, I assume it's a long form. :tired_face:
Apart from the few points I've mentioned, you sure did a great job on your UIs.  :clap: :clap: :clap:

:sparkles: *Tip* :sparkles: 
Integrate Code climate to help you review your code standards.

2018-02-28 21:53 UTC, mmosoroohh commented
It's long code but looks great. Well done indentation thus making the code look visible and clear.

2018-03-01 07:16 UTC, muthash commented
@JoshuaOndieki Thanks for the feedback. In production the sitemap links in the index page will not be there. I inserted them to guide in the review instead of having to enter the dashboard links manually in the browser since the pages are not functional at the moment.

2018-03-03 10:49 UTC, merged